# Generated by Django 3.2.4 on 2021-06-30 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutsec', models.CharField(max_length=11)),
                ('nombre_sec', models.CharField(max_length=80)),
                ('apaterno_sec', models.CharField(max_length=80)),
                ('amaterno_sec', models.CharField(max_length=80)),
                ('correo_sec', models.EmailField(max_length=200)),
                ('fecha_nacimiento_sec', models.CharField(max_length=80)),
                ('sexo_sec', models.CharField(max_length=20)),
                ('edad_sec', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad')),
                ('nombreM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_pac', models.CharField(max_length=11)),
                ('nombre_pac', models.CharField(max_length=80)),
                ('apaterno_pac', models.CharField(max_length=80)),
                ('amaterno_pac', models.CharField(max_length=80)),
                ('correo_pac', models.EmailField(max_length=200)),
                ('fecha_nacimiento_pac', models.CharField(max_length=80)),
                ('sexo_pac', models.CharField(max_length=20)),
                ('edad_pac', models.IntegerField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad')),
                ('nombreM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=11)),
                ('valor_consulta', models.IntegerField()),
                ('rut_pac', models.CharField(max_length=11)),
                ('fecha_recaudo_boleta', models.CharField(max_length=80)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad')),
                ('nombreM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
            ],
        ),
    ]
